#!/bin/sh
#
# @name Colugo Y H-Frame VTOL
#
# @type Y H-Frame VTOL
# @class VTOL
#
# @maintainer colugo
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
# @output AUX1 Aileron 1
# @output AUX2 Aileron 2
# @output AUX3 Elevator
# @output AUX4 Rudder
# @output AUX5 Throttle
#

. ${R}etc/init.d/rc.vtol_defaults

param set-default SYS_CTRL_ALLOC 1
param set-default CA_AIRFRAME 10

param set-default CA_ROTOR_COUNT 5
param set-default CA_ROTOR0_PX 0.78
param set-default CA_ROTOR0_PY 0.48
param set-default CA_ROTOR0_KM 0.0  # No yaw contribution
param set-default CA_ROTOR0_AX 0.0  # X-axis torque disabled
param set-default CA_ROTOR1_PX -0.78
param set-default CA_ROTOR1_PY -0.48
param set-default CA_ROTOR1_KM 0.05  # Yaw contribution active
param set-default CA_ROTOR1_AY 0.0   # Y-axis torque disabled (no roll)
param set-default CA_ROTOR2_PX 0.78
param set-default CA_ROTOR2_PY -0.48
param set-default CA_ROTOR2_KM 0.0  # No yaw contribution
param set-default CA_ROTOR2_AX 0.0  # X-axis torque disabled
param set-default CA_ROTOR3_PX -0.78
param set-default CA_ROTOR3_PY 0.48
param set-default CA_ROTOR3_KM -0.05 # Yaw contribution active
param set-default CA_ROTOR3_AY 0.0   # Y-axis torque disabled (no roll)
param set-default CA_ROTOR4_AX 1.0
param set-default CA_ROTOR4_AZ 0.0
param set-default CA_ROTOR4_PX 0.2

param set-default CA_SV_CS_COUNT 4
param set-default CA_SV_CS0_TYPE 1
param set-default CA_SV_CS0_TRQ_R -0.5
param set-default CA_SV_CS1_TYPE 2
param set-default CA_SV_CS1_TRQ_R 0.5
param set-default CA_SV_CS2_TYPE 3
param set-default CA_SV_CS2_TRQ_P 1.0
param set-default CA_SV_CS3_TRQ_Y 1.0
param set-default CA_SV_CS3_TYPE 4

param set-default VT_TYPE 2
param set-default VT_MOT_ID 1234
param set-default VT_FW_MOT_OFFID 1234

param set-default MAV_TYPE 22

# PWM output configuration
param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104
param set-default PWM_MAIN_FUNC5 105
param set-default PWM_MAIN_FUNC6 201
param set-default PWM_MAIN_FUNC7 202
param set-default PWM_MAIN_FUNC8 203
param set-default PWM_MAIN_FUNC9 204

# Fixed-wing tuning parameters
param set-default FW_L1_PERIOD 12
param set-default FW_MAN_P_MAX 30
param set-default FW_PR_FF 0.2
param set-default FW_PR_P 0.9
param set-default FW_PSP_OFF 2
param set-default FW_P_LIM_MAX 32
param set-default FW_P_LIM_MIN -15
param set-default FW_RR_FF 0.1
param set-default FW_RR_P 0.3
param set-default FW_THR_CRUISE 0.25
param set-default FW_THR_MAX 0.6
param set-default FW_THR_MIN 0.05
param set-default FW_T_CLMB_MAX 8
param set-default FW_T_SINK_MAX 2.7
param set-default FW_T_SINK_MIN 2.2

# Multicopter tuning parameters
param set-default MC_ROLLRATE_P 0.3
param set-default MC_YAW_P 1.6

param set-default MIS_TAKEOFF_ALT 11

param set-default MPC_ACC_HOR_MAX 2
param set-default MPC_XY_P 0.8
param set-default MPC_XY_VEL_P_ACC 3
param set-default MPC_XY_VEL_I_ACC 4
param set-default MPC_XY_VEL_D_ACC 0.1

param set-default NAV_ACC_RAD 5

# VTOL transition parameters
param set-default VT_FWD_THRUST_EN 4
param set-default VT_F_TRANS_THR 0.75
param set-default VT_B_TRANS_DUR 18
param set-default VT_ARSP_BLEND 7.0
param set-default VT_ARSP_TRANS 13.0
param set-default VT_TRANS_TIMEOUT 25.0
param set-default VT_TRANS_MIN_TM 8.0
param set-default VT_F_TR_OL_TM 9.0
param set-default VT_F_TRANS_DUR 12.0

set MIXER_FILE etc/mixers-sitl/colugo_y_vtol_sitl.main.mix
set MIXER custom

set PWM_OUT 1234
